I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 146, in script call
    call wake_up from _call_wake_up
  File "game/script.rpy", line 164, in script call
    call wu_day from _call_wu_day
  File "game/days.rpy", line 62, in script
    wumauh "Not bad!!"
SyntaxError: unexpected character after line continuation character (<none>, line 1)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 146, in script call
    call wake_up from _call_wake_up
  File "game/script.rpy", line 164, in script call
    call wu_day from _call_wu_day
  File "game/days.rpy", line 62, in script
    wumauh "Not bad!!"
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\character.py", line 1438, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1207, in py_eval
    code = py_compile(code, 'eval')
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1144, in py_compile
    raise e
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1081, in py_compile
    raise orig_e
  File "C:\Users\Russel\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1073, in py_compile
    tree = compile(source, filename, py_mode, ast.PyCF_ONLY_AST | flags, 1)
SyntaxError: unexpected character after line continuation character (<none>, line 1)

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
Wumauhen 1.0
Thu Nov 21 21:34:38 2024
